*** Settings ***
Resource  ./API/Endpoints/OnecallEndpoint.robot
Resource  ./API/Endpoints/WeatherEndpoint.robot
Resource  ./API/ApiSteps.robot
Resource  ./WEB/PO/TopNav.robot
Resource  ./WEB/PO/LoginPage.robot
Resource  ./WEB/PO/HomePage.robot
Resource  ./WEB/PO/MainPage.robot
Resource  ./WEB/PO/UserSettingsPage.robot
Resource  ./WEB/WebSteps/LoginSteps.robot
Resource  ./WEB/WebSteps/MainPageSteps.robot
Resource  ./WEB/WebSteps/UserSettingsSteps.robot
Resource  ./MixedSteps.robot
Resource  ./Global_Variables.robot
Library  ./ConvertTools.py
Library  SeleniumLibrary
Library  String
Library  RequestsLibrary
Library  JSONLibrary
Library  Collections
Library  DateTime